lib/event_planning_web/router.ex
defmodule EventPlanningWeb.Router do
  use EventPlanningWeb, :router

  alias EventPlanning.Models.User
  alias EventPlanning.Repo

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", EventPlanningWeb do
    pipe_through(:browser)

    resources("/", PageController, only: [:new, :create, :delete])
  end

  scope "/", EventPlanningWeb do
    pipe_through(:browser)

    resources("/users", UserController) do
      resources("/event", EventController, except: [:index])
      get("/my_schedule", EventController, :my_schedule)
      post("/my_schedule", EventController, :my_schedule)
      get("/next_event", EventController, :next_event)
    end
  end

  scope "/", EventPlanningWeb do
    pipe_through([:browser])

    get("/home", HomeController, :index)
  end

  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through(:browser)
      live_dashboard("/dashboard", metrics: EventPlanningWeb.Telemetry)
    end
  end

  defp authenticate_user(conn, _) do
    case get_session(conn, :user_id) do
      nil ->
        conn
        |> Phoenix.Controller.put_flash(:error, "Login required")
        |> redirect(to: Routes.page_path(conn, :new))
        |> halt()

      user_id ->
        assign(conn, :current_user, Repo.get!(User, user_id))
    end
  end
end

# no match of right hand side value: %{"_csrf_token" => "PgBRCklHAxQxHj5UPSITfQkFMQgHKToMlX0A36PDenreywI09NHPJcPm", "page" => %{"categories_id" => "year"}}

lib/event_planning_web/views/layout_view.ex
defmodule EventPlanningWeb.LayoutView do
  use EventPlanningWeb, :view

  def current_user(conn) do
    Plug.Conn.get_session(conn, :current_user)
  end
end

lib/event_planning_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>EventPlanning · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <li><li>
    <%= if user = current_user(@conn) do %>
      <br>
        <span><%= link "Profile", to: Routes.user_path(@conn, :show, user.id) %></span>
        <span><%= link "Edit", to: Routes.user_path(@conn, :edit, user.id) %></span>
        <span><%= link "Log out", to: Routes.page_path(@conn, :delete, user.id), method: :delete %></span>
      <% else %>
        <%= link "Log in", to: Routes.page_path(@conn, :new) %>
      <% end %>
      </li>
          </ul>
        </nav>
        <a href="https://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
  </body>
</html>